version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: int221-mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - int221-net

  backend:
    build:
      context: ./INT221-BACKEND
      dockerfile: Dockerfile
    container_name: int221-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - mysql
    networks:
      - int221-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: int221-frontend
    depends_on:
      - backend
    volumes:
      - frontend-dist:/app/dist
    command: [ "echo", "frontend build completed" ]
    networks:
      - int221-net

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    container_name: int221-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - int221-net

volumes:
  mysql-data:
  frontend-dist:

networks:
  int221-net: